site_name: ehp-sn
site_description: Entorhinal-Hippocampal-Prefrontal Circuit for Spatial Navigation library
site_author: Borja Esteban Sanchis
docs_dir: docs

theme:
  name: mkdocs

plugins:
  - search
  - mkdocstrings:

nav:
  - Home: _index.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
